import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} `}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-neutral-300 p-4 antialiased`}
      >
        <div
          className={cn(
            "relative mx-auto flex flex-col",
            "h-[calc(100dvh-2rem)] max-h-[844px] max-w-sm" // iPhone 12 Pro
          )}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
